export const LOAD_ITEMS = "LOAD_ITEMS";

export const ADD_TO_CART = "ADD_TO_CART";
export const UPDATE_CARTITEM_QUANTITY = "UPDATE_CARTITEM_QUANTITY";
export const REMOVE_ITEM_FROM_CART = "REMOVE_ITEM_FROM_CART";

export const LOGIN_USER = "LOGIN_USER";
export const SIGNUP_USER = "SIGNUP_USER";
export const UPDATE_USER_ADDRESS = "UPDATE_USER_ADDRESS";
export const UPDATE_USER_PAYMENT = "UPDATE_USER_PAYMENT";

export const SUBMIT_ORDER = "SUBMIT_ORDER";
